version: '3.3'

services:
  api:
    build:
      # context: ./api
      # dockerfile: ../docker/api/Dockerfile
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      # - ./.env.prod
      - .env.prod
    command: gunicorn --bind 0.0.0.0:5000 traceability:app    
  frontend:
    build:
      # context: ./frontend
      # dockerfile: ../docker/frontend/Dockerfile.prod
      context: .
      dockerfile: docker/frontend/Dockerfile.prod
    depends_on:
      - api
    ports:
      - "80:80"    