version: '3.3'

services: 
  api_v2:
    build:      
      context: .
      dockerfile: docker/api_v2/Dockerfile.prod
    env_file:      
      - .env.prod
    command: gunicorn --bind 0.0.0.0:5001 traceability:app    
  frontend:
    build:      
      context: .
      dockerfile: docker/frontend/Dockerfile.prod
    depends_on:
      - api_v2
    ports:
      - "80:80"    