version: '3.3'

services:
  web:
    build: ./web
    command: python traceability.py run -h 0.0.0.0
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    
