version: '3.3'

services:
  # api_old:
  #   build: 
  #     context: ./api   
  #     dockerfile: ../docker/api/Dockerfile.dev
  #   command: python traceability.py run -h 0.0.0.0:5000
  #   volumes:
  #     - ./api/:/usr/src/app/
  #   ports:
  #     - 5000:5000
  #   env_file:
  #     - ./.env.dev
  api_new:
    build:
      # context: ./api_v2
      # dockerfile: ../docker/api_v2/Dockerfile.dev
      context: .
      dockerfile: docker/api_v2/Dockerfile.prod
    command: python traceability.py run -h 0.0.0.0:5001
    # volumes:
    #   - ./api/:usr/src/app/
    ports:
      - 5001:5001
    env_file:
    - ./.env.dev
    networks:
      - traceability
#   front:
#     build: 
#       context:  ./front
#       dockerfile: ./Dockerfile.dev
#     depends_on:
#       - web
#     ports:
#       - "3000:3000"
#     networks:
#       - traceability
#     links:
#       - "web"
#     command: npm start

networks:
    traceability:
        driver: bridge