version: '3.3'

services:
  web:
    build: ./web
    command: gunicorn --bind 0.0.0.0:5000 traceability:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web