FROM node:16-alpine as build-step

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY ./package*.json ./
COPY ./tsconfig.json ./
COPY ./src ./src
COPY ./public ./public
RUN npm install npm@8.7.0
RUN rm -rf /usr/local/lib/node_modules/npm
RUN mv node_modules/npm /usr/local/lib/node_modules/npm

# RUN npm install
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY ./nginx.default.conf /etc/nginx/conf.d/default.conf